services:
  - type: web
    name: aduanas-duca-api
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: aduanas-db
          property: connectionString
databases:
  - name: aduanas-db
    plan: free
